package com.litmethod.android.models.ClassDetails

data class Data6(
    val accessories: List<Equipment>,
    val awsUrl: String,
    val classRatting: ClassRatting,
    val class_type: String,
    val content: String,
    val date: String,
    val devices: List<Device>,
    val difficultyRating: String,
    val equipment: List<Equipment>,
    val equipment_video: List<EquipmentVideo>,
    val getDurations: String,
    val getInstructor: String,
    val getLevelName: String,
    val get_discussion_id: String,
    val id: String,
    val instructor_info: List<InstructorInfo>,
    val isEnroll: Boolean,
    val isLive: Boolean,
    val isSave: Boolean,
    val isViewed: Boolean,
    val mediaid: String,
    val muscle_groups: String,
    val muscle_image: String,
    val radioStation: String,
    val show_feed_fm: Boolean,
    val thumbnail: String,
    val title: String,
    val videoCategory: List<VideoCategory>,
    val videoUrl: String
)